// Copyright 2015, Beeswax.IO Inc.
// Author: ramr@beeswax.com
//
// Protocol buffer defining a unique EventId

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: beeswax/base/eventid.proto

package base

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EventId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32 bits of md5 hash
	Hostid    *uint32 `protobuf:"varint,1,opt,name=hostid" json:"hostid,omitempty"`
	Tid       *uint32 `protobuf:"varint,2,opt,name=tid" json:"tid,omitempty"`
	Timestamp *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// Impression index within the request
	ImpIdx *uint32 `protobuf:"varint,4,opt,name=imp_idx,json=impIdx" json:"imp_idx,omitempty"`
}

func (x *EventId) Reset() {
	*x = EventId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeswax_base_eventid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventId) ProtoMessage() {}

func (x *EventId) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_base_eventid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventId.ProtoReflect.Descriptor instead.
func (*EventId) Descriptor() ([]byte, []int) {
	return file_beeswax_base_eventid_proto_rawDescGZIP(), []int{0}
}

func (x *EventId) GetHostid() uint32 {
	if x != nil && x.Hostid != nil {
		return *x.Hostid
	}
	return 0
}

func (x *EventId) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *EventId) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *EventId) GetImpIdx() uint32 {
	if x != nil && x.ImpIdx != nil {
		return *x.ImpIdx
	}
	return 0
}

// Next Tag: 5
type AdGroupId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuzzKey    *string `protobuf:"bytes,1,opt,name=buzz_key,json=buzzKey" json:"buzz_key,omitempty"`
	Accountid  *uint64 `protobuf:"varint,2,opt,name=accountid" json:"accountid,omitempty"`
	Campaignid *uint64 `protobuf:"varint,3,opt,name=campaignid" json:"campaignid,omitempty"`
	Lineitemid *uint64 `protobuf:"varint,4,opt,name=lineitemid" json:"lineitemid,omitempty"`
}

func (x *AdGroupId) Reset() {
	*x = AdGroupId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeswax_base_eventid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdGroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroupId) ProtoMessage() {}

func (x *AdGroupId) ProtoReflect() protoreflect.Message {
	mi := &file_beeswax_base_eventid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroupId.ProtoReflect.Descriptor instead.
func (*AdGroupId) Descriptor() ([]byte, []int) {
	return file_beeswax_base_eventid_proto_rawDescGZIP(), []int{1}
}

func (x *AdGroupId) GetBuzzKey() string {
	if x != nil && x.BuzzKey != nil {
		return *x.BuzzKey
	}
	return ""
}

func (x *AdGroupId) GetAccountid() uint64 {
	if x != nil && x.Accountid != nil {
		return *x.Accountid
	}
	return 0
}

func (x *AdGroupId) GetCampaignid() uint64 {
	if x != nil && x.Campaignid != nil {
		return *x.Campaignid
	}
	return 0
}

func (x *AdGroupId) GetLineitemid() uint64 {
	if x != nil && x.Lineitemid != nil {
		return *x.Lineitemid
	}
	return 0
}

var File_beeswax_base_eventid_proto protoreflect.FileDescriptor

var file_beeswax_base_eventid_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x65, 0x65, 0x73, 0x77, 0x61, 0x78, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x6a, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x6d, 0x70, 0x49, 0x64, 0x78, 0x22, 0x84,
	0x01, 0x0a, 0x09, 0x41, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x75, 0x7a, 0x7a, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x75, 0x7a, 0x7a, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x69, 0x74, 0x65,
	0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x69,
	0x74, 0x65, 0x6d, 0x69, 0x64, 0x42, 0x12, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x65, 0x65,
	0x73, 0x77, 0x61, 0x78, 0x2e, 0x62, 0x61, 0x73, 0x65,
}

var (
	file_beeswax_base_eventid_proto_rawDescOnce sync.Once
	file_beeswax_base_eventid_proto_rawDescData = file_beeswax_base_eventid_proto_rawDesc
)

func file_beeswax_base_eventid_proto_rawDescGZIP() []byte {
	file_beeswax_base_eventid_proto_rawDescOnce.Do(func() {
		file_beeswax_base_eventid_proto_rawDescData = protoimpl.X.CompressGZIP(file_beeswax_base_eventid_proto_rawDescData)
	})
	return file_beeswax_base_eventid_proto_rawDescData
}

var file_beeswax_base_eventid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beeswax_base_eventid_proto_goTypes = []interface{}{
	(*EventId)(nil),   // 0: base.EventId
	(*AdGroupId)(nil), // 1: base.AdGroupId
}
var file_beeswax_base_eventid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beeswax_base_eventid_proto_init() }
func file_beeswax_base_eventid_proto_init() {
	if File_beeswax_base_eventid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beeswax_base_eventid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeswax_base_eventid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdGroupId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beeswax_base_eventid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeswax_base_eventid_proto_goTypes,
		DependencyIndexes: file_beeswax_base_eventid_proto_depIdxs,
		MessageInfos:      file_beeswax_base_eventid_proto_msgTypes,
	}.Build()
	File_beeswax_base_eventid_proto = out.File
	file_beeswax_base_eventid_proto_rawDesc = nil
	file_beeswax_base_eventid_proto_goTypes = nil
	file_beeswax_base_eventid_proto_depIdxs = nil
}
